//MATH IS OBJECT AS IT SELF
// console.log(Math);
// console.log(math.abs (-4));
// console.log(math.round(4.6));//IMP

// let mycreatedate =new Date("14-06-2000")

// // console.log(mycreatedate.toLocaleString());

// // let mytimestamp= date.now()

// console.log(mytimestamp);
// console.log(mycreatedate.getTime());

// let mycreateDate= new Date("12-06-2000")
// // let mytimestamp= date. now()

// console.log(mytimestamp);
// console.log(mycreateDate.getTime());
// console.log(Date.now());


// let mycreateDate = new Date("01-14-2023")

// let mytimestamp = Date.now()
// console.log(Date.now() /1000);
// //common interview queation but those come into the 693459681.262 decimal value 
// //so that reasone use math.floar get convert it into the some seconde in value 

let newDate = new Date()
console.log(newDate);
// 2023-08-31T05:31:23.407Z

console.log(newDate.getMonth());
// 7

console.log(newDate.getDay());
// 4

